name: Baue Windows & macOS Version

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # 1. Code herunterladen
      - name: Lade den Quellcode herunter
        uses: actions/checkout@v4

      # 2. Python einrichten
      - name: Installiere Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Python-Pakete installieren
      - name: Installiere Python-Pakete
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Windows: Inno Setup & Nmap vorbereiten
      - name: Windows-spezifische Vorbereitungen
        if: runner.os == 'Windows'
        run: |
          # Installiere Inno Setup für den Installer-Bau
          choco install innosetup --version=6.2.2 -y
          
          # Definiere die URL zum offiziellen Nmap-Installer
          $NMAP_URL = "https://nmap.org/dist/nmap-7.95-setup.exe"
          $NMAP_INSTALLER_PATH = "nmap-setup.exe"
          
          # Lade den Installer direkt von nmap.org herunter
          echo "Lade Nmap von $NMAP_URL herunter..."
          Invoke-WebRequest -Uri $NMAP_URL -OutFile $NMAP_INSTALLER_PATH
          
          # Führe den heruntergeladenen Installer im "Silent Mode" aus
          echo "Installiere Nmap im Silent Mode..."
          Start-Process -FilePath $NMAP_INSTALLER_PATH -ArgumentList "/S" -Wait
          
          # Gib dem Installer einen Moment Zeit, um fertig zu werden
          Start-Sleep -Seconds 10
          
          # Erstelle einen temporären Ordner für die installierten Nmap-Dateien
          New-Item -ItemType Directory -Force -Path "dependencies/nmap_unpacked"
          
          # Kopiere die installierten Nmap-Dateien aus dem Programme-Ordner
          echo "Kopiere installierte Nmap-Dateien..."
          Copy-Item -Path "C:\Program Files (x86)\Nmap\*" -Destination "dependencies\nmap_unpacked" -Recurse
        shell: pwsh

      # 5. macOS: Nmap installieren
      - name: macOS-spezifische Vorbereitungen
        if: runner.os == 'macOS'
        run: brew install nmap

      # 6. Anwendung mit PyInstaller bauen
      - name: Führe das PyInstaller Build-Skript aus
        run: python main.py --build

      # 7. Windows Installer mit Inno Setup erstellen
      - name: Erstelle Windows Installer
        if: runner.os == 'Windows'
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\iscc.exe" "setup.iss"
        shell: pwsh

      # 8. Ergebnis verpacken und Outputs festlegen
      - name: Ergebnis verpacken und Outputs festlegen
        id: package
        run: |
          if ("${{ runner.os }}" -eq "Windows") {
            echo "ASSET_PATH=Output/Netzwerk-Scanner-Pro-Setup.exe" >> $env:GITHUB_OUTPUT
            echo "ASSET_NAME=Netzwerk-Scanner-Pro-Windows-Setup.exe" >> $env:GITHUB_OUTPUT
          }
          else {
            $ASSET_NAME = "Netzwerk-Scanner-Pro-macOS.zip"
            cd dist
            zip -r ../$ASSET_NAME "Netzwerk-Scanner Pro.app"
            cd ..
            echo "ASSET_PATH=$ASSET_NAME" >> $env:GITHUB_OUTPUT
            echo "ASSET_NAME=$ASSET_NAME" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh
      
      # 9. Fertiges Paket zum Release hochladen
            # 9. Fertiges Paket zum Release hochladen
      - name: Lade fertiges Paket hoch (via GitHub CLI)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ steps.package.outputs.ASSET_PATH }} --clobber
