# .github/workflows/test-workflow.yml

name: Einfacher Test-Workflow

# Trigger: Starte bei JEDEM Push zum main-Branch
on:
  push:
    branches: [ main ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sage Hallo
        run: echo "Hallo Welt! Der Test-Workflow wurde erfolgreich gestartet."
